logging:
  level:
    root: info

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql80.eulerlcs.io:33068/hello?useUnicode=true&useSSL=true&useCharacterEncoding=utf-8&serverTimezone=JST
    username: user01
    password: 123456
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    